test: k6 yml fix (#670)

diff --git a/.github/workflows/k6-tests.yml b/.github/workflows/k6-tests.yml
--- a/.github/workflows/k6-tests.yml
+++ b/.github/workflows/k6-tests.yml
@@ -5,15 +5,14 @@ on:
     types:
       - 'vercel.deployment.success'
   workflow_dispatch:
-    host:
-      branch:
+    inputs:
+      host:
         description: 'Set the host'
         required: true
         default: ''
 
 jobs:
   k6-preview-tests:
-    if: ${{ github.event_name == 'repository_dispatch' || github.event.inputs.host != '' }}
     runs-on: ubuntu-latest
     env:
       ENV_HOST: ${{ github.event.inputs.host || github.event.client_payload.url }}
@@ -21,11 +20,14 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Install k6
-        run: |
-          curl https://github.com/grafana/k6/releases/download/v1.4.0/k6-v1.4.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
+      - name: Setup k6 browser environment
+        uses: grafana/setup-k6-action@v1
+        with:
+          k6-version: '1.4.0'
+          browser: true
 
       - name: Install k6 extensions
+        working-directory: e2e-tests/k6
         run: |
           go install go.k6.io/xk6/cmd/xk6@latest
           export PATH=$(go env GOPATH)/bin:$PATH
@@ -34,7 +36,7 @@ jobs:
       - name: Install dependencies
         working-directory: e2e-tests/k6
         run: |
-          yarn install          
+          yarn install      
 
       - name: Run k6 tests
         working-directory: e2e-tests/k6
@@ -45,7 +47,19 @@ jobs:
 
       - name: Request log
         run: |
-          cat e2e-tests/k6/logs/requests.log    
+          if find e2e-tests/k6/logs -maxdepth 1 -name "requests.log" | grep -q .; then
+            cat e2e-tests/k6/logs/requests.log
+          else
+            echo "### ⚠️ Test errors" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "See more details in the workflow" >> $GITHUB_STEP_SUMMARY
+            echo "⚠️ No requests log is found, failing the job."
+            exit 1
+          fi
+
+      - name: Notify Slack
+        run: |
+          ./e2e-tests/k6/integration/slack_notification.sh ${{ secrets.ATB_SLACK_TOKEN }} e2e_tests ${{ github.run_id }}
 
       - name: Fail on any errors
         run: |
